version: '3'

services:
  hotspot-analysis:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./results:/app/results
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run src/visualization/app.py --server.port=8501 --server.address=0.0.0.0 